### PR TITLE
typescript support ☑

### PR DESCRIPTION
**Pull request by davidkhierl**
changed project to typescript and did my best to type the selection JSON file from icomoon.io, I quite did the similar approach in my existing project when this package still doesn't support typescript.

### CODE REVIEW

**Comment by aykutkardas** [comment]
Thanks for this work. I will evaluate this in more detail. I am waiting for a more suitable time for this. @davidkhierl

**Comment by aykutkardas** [comment]
image

I generated an selection.json file and tried it. But I am getting some errors. What is this all about? @davidkhierl

**Comment by davidkhierl** [comment]
Hmmm that’s odd seems like the selection.json got updated it have different
properties now

**Comment by aykutkardas** [comment]
> Hmmm that’s odd seems like the selection.json got updated it have different properties now

I understand the cause of that problem, but there are a number of other shortcomings. Your development is almost available, but still a huge change. I'll merge this once I'm sure enough.

**Comment by davidkhierl** [comment]
I understand, some of the method won’t work anymore especially the getting
of the current icon and path as the json file have different properties
now. A quick workaround is make the iconSet props to a generic type or cast
it directly

**Comment by davidkhierl** [comment]
updated the "iconSet" types, if this got pushed thru I'm planning to have it's own context api for the selection.json so we can utilize hooks for ease in the future, please let me know what you think

**Pull request closed without merging**
